### ISSUE TITLE
Ask Question - Do you have any method for regular blade? 

### ISSUE THREAD

**Issue by baiqunicui** [redbastie/tailwire#1]
I'm trying you composer and wondering about, do you have any method for regular blade and component not using html inside PHP method? cause for frontend developer sometimes more easily to work with html, blade and component method? 
Maybe change (View $v) to blade, would be amazing if can, thank you

**Comment by redbastie** [comment]
no the whole point of this package is to use php to build html

if you want to use blade, use my other package: https://github.com/redbastie/skele
