### ISSUE TITLE
Error Method Redbastie\Tailwire\Directives\IfDirective::__toString() must return a string value 

### ISSUE THREAD

**Issue by wi-wi** [redbastie/tailwire#10]
at my pc TailWire runs fine with php8.
at my hosting server that I access through ssh and that has php7.4 but **no php8** (yet) and **no npm** available I get this error.
probably I need to be patient until they upgrade to php8 in a few months. Meanwhile, might the error below be caused by the php7.4 version?  
**Error**
*Method Redbastie\Tailwire\Directives\IfDirective::__toString() must return a string value*
--------------
    59
    vendor/redbastie/tailwire/src/Elements/ContentElement.php
    :14
    58
    Redbastie\Tailwire\Elements\ContentElement
    :14

    55
    app/Components/Layouts/App.php
    App\Components\Layouts\App
    :42

    40
    app/Http/Middleware/RedirectIfAuthenticated.php
    App\Http\Middleware\RedirectIfAuthenticated
    :30

    1
    public/index.php
    :52

**Comment by redbastie** [comment]
Using PHP 8?

**Comment by redbastie** [comment]
Tailwire requires PHP 8.
