### ISSUE TITLE
Exception when using php artisan tailwire:crud

### ISSUE THREAD

**Issue by artticks** [redbastie/tailwire#14]
composer require redbastie/tailwire
php artisan tailwire:install
php artisan tailwire:crud Plan

   ErrorException 

  Object of class Illuminate\Support\Stringable could not be converted to int

  at vendor/laravel/framework/src/Illuminate/Support/Str.php:580
    576▕         if ($search === '') {
    577▕             return $subject;
    578▕         }
    579▕ 
  ➜ 580▕         $position = strrpos($subject, $search);
    581▕ 
    582▕         if ($position !== false) {
    583▕             return substr_replace($subject, $replace, $position, strlen($search));
    584▕         }

      +15 vendor frames 
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by tangjh** [comment]
Oh using php 7.4.  Must it be PHP 8?

**Comment by tangjh** [comment]
ok.  working in php 8.
closing issue.
