### ISSUE TITLE
Method Redbastie\Tailwire\Directives\IfDirective::__toString() must return a string value

### ISSUE THREAD

**Issue by crazedVic** [redbastie/tailwire#5]
So to get /services working I installed tailwire:auth
```
C:\Users\user\projects\test-skele>php artisan tailwire:auth
Created file: app\Components\Auth\Login.php
Created file: app\Components\Auth\Logout.php
Created file: app\Components\Auth\PasswordForgot.php
Created file: app\Components\Auth\PasswordReset.php
Created file: app\Components\Auth\Register.php
Created file: app\Components\Home.php
Auth generated! http://localhost:8000/login
```
no errors.
went back to browser http://127.0.0.1:8000/login
```
::implode
C:\Users\user\projects\test-skele\vendor\redbastie\tailwire\src\Elements\ContentElement.php:14
<?php

 namespace Redbastie\Tailwire\Elements;

class ContentElement extends BaseElement
{
    protected $tag, $content;

   public function __construct($tag, ...$content)
    {
        parent::__construct();
        $this->tag = $tag;
        $this->content = implode($content);
    }
}
```

**Comment by redbastie** [comment]
So, it looks like something is off with the `$v->if` statement inside of the app layout component here. It should be returning a string regardless of being logged in or not.

Are you using PHP 8?

**Comment by crazedVic** [comment]
i commented out this in App.php and the error went away:

```
//                $v->if(Route::has('login'),
//                    fn() => $v->if(Auth::guest(),
//                        fn() => $v->nav(
//                            $v->a('Login')->href(route('login'))->class('text-blue-600'),
//                            $v->a('Register')->href(route('register'))->class('text-blue-600')
//                        )->class('flex space-x-4')
//                    )->else(
//                        fn() => $v->nav(
//                            $v->a('Home')->href(route('home'))->class('text-blue-600'),
//                            $v->a('Logout')->href(route('logout'))->class('text-blue-600')
//                        )->class('flex space-x-4')
//                    )
//                )
```

**Comment by redbastie** [comment]
Yeah its coming from the `$v->if` statement.

Notice how it's using PHP 8 arrow syntax. I can only guess you aren't running PHP 8?

If not, it's easy to install in Laragon: https://forum.laragon.org/topic/166/tutorial-how-to-add-another-php-version-php-7-4-php-8-0-updated

I use mac so updating PHP for me takes 1 terminal command :/

**Comment by crazedVic** [comment]
ah you're on v8, that would explain that. I'm still on v7.4.

**Comment by redbastie** [comment]
I have a feeling that if you used PHP 8 all of your issues would be resolved.

PHP 8 required to use tailwire as per the docs.

**Comment by crazedVic** [comment]
I don't create packages, but there must be a way to enforce min php version in composer.json?  Maybe something like:
```
require": {
        "php": "8.0"
    }
```

**Comment by redbastie** [comment]
Yes, you're right. I should add this to the composer.json.

**Comment by redbastie** [comment]
Can you try everything with PHP 8?

I understand if you don't want to upgrade. But this package promotes stuff available only in PHP 8, like the arrow function you saw above. It provides a cleaner syntax for writing stuff in the view method.

**Comment by crazedVic** [comment]
yeah i'll give it a shot.
