### ISSUE TITLE
->after() not working as intended on migration

### ISSUE THREAD

**Issue by crazedVic** [redbastie/tailwire#6]
$schemaManager->alterTable($tableDiff);

Noticed that timezone field is always showing up after timestamps, I prefer timestamps at the end.  I added ->after('password') but it errors out because the code is actually creating a temp table and then doing a comparison and updating the existing schema with differences found in temp table.

So altering the migration in User for example seems to always  put any new fields on the end:

```
     $table->id();
        $table->string('name');
        $table->string('email')->unique();
        $table->string('password');
        $table->string('timezone')->nullable();
        $table->string('surname')->nullable();
        $table->rememberToken();
        $table->timestamps();
```

will add surname and timezone after timestamps.  after just errors out, for obvious reasons.

**Comment by redbastie** [comment]
Use --fresh and it will restructure the table and wipe the data. 

If you don't want to wipe the data, I would have to refactor the command.

**Comment by crazedVic** [comment]
Suddenly I understand the reasoning behind this: 

```
$this->deleteFiles([
            'database/migrations/2014_10_12_000000_create_users_table.php',
            'resources/views/welcome.blade.php',
        ]);
``` 

i looked at the Doctrine/DBAL code and I think a refactor would not be worth the effort.  Closing.
