### ISSUE TITLE
Error when installing Tailwire

### ISSUE THREAD

**Issue by lodzax** [redbastie/tailwire#7]
Hie Kev, I keep getting this error when I try to install Tailwire, pliz help

![image](https://user-images.githubusercontent.com/35598651/107746688-e9916b00-6d1e-11eb-9f2e-a023dbd159d3.png)

**Comment by redbastie** [comment]
Ah yeah, this is an issue with windows that has been reported. It's because windows uses DOS-style backslashes for folder paths. I'll see if I can come up with a solution.

**Comment by redbastie** [comment]
I just pushed 2.1.9, please update to that version of tailwire using `composer update`. Then let me know if it's fixed now or not. I just made a change to replace forward slashes with backslashes for windows.

**Comment by lodzax** [comment]
Great, thanks for the response. I've managed to install, thanks to your update. However, when I tried to run the app for the first time, I get the error on the attached screenshot and I'm stuck there. Pliz assist.
![image](https://user-images.githubusercontent.com/35598651/107855716-97d70680-6e2c-11eb-8c80-a2b337a343de.png)

**Comment by redbastie** [comment]
You must use PHP 8 with Tailwire.

I'm guessing you're using PHP 7.4 or something lower.

**Comment by lodzax** [comment]
Ohh...yes, you're right. I am using 7.4. Let me update and I'll let you know how it goes. Thanks very much, great work. Pliz keep it up !!

**Comment by lodzax** [comment]
Hey Kev, u were right, after upgrading my PHP to 8, everything went smoothly and the app is running as it should be. Once again, thanks very much for everything.
