### ISSUE TITLE
Missing: Created file: app/Components/User/Index.php  

### ISSUE THREAD

**Issue by wi-wi** [redbastie/tailwire#9]
After
php artisan tailwire:auth
Missing
Created file: app/Components/User/Index.php
Created file: app/Components/User/Read.php
Created file: app/Components/User/Save.php
========================================

h@h ...3tb/www/Tailwire-demo % php artisan tailwire:auth
Created file: app/Components/Auth/Login.php
Created file: app/Components/Auth/Logout.php
Created file: app/Components/Auth/PasswordForgot.php
Created file: app/Components/Auth/PasswordReset.php
Created file: app/Components/Auth/Register.php
Created file: app/Components/Home.php
Auth generated! http://tailwire-demo.test/login

**Comment by redbastie** [comment]
Did you run tailwire:install first?

Also, what OS? And are you using PHP 8?

**Comment by wi-wi** [comment]
I resolved the issue by running:
php artisan tailwire:crud user
========
& yes did run install:
php artisan tailwire:install
OS:
linux mint 20 / php 8

===========
Other issue, when I ran " npm run production " it broke the css -> in that form fields /register - /login were no longer visible, yet clicking blindly made them appear again. firefox browser. cross checked with chrome
I will check that tomorrow.
====
finding tailwire awesome. thanks for now.

**Comment by redbastie** [comment]
For the NPM run production, check the tailwind config. I'm guessing it's purging everything.

**Comment by wi-wi** [comment]
Hi, ran it again with a fresh install and the problem did not reproduce. case closed. Thanks

this is in my fresh installed  tailwind.config.js

const colors = require('tailwindcss/colors');

module.exports = {
    purge: [
        './app/Components/**/*.php',
        './resources/**/*.blade.php',
        './resources/**/*.js',
    ],
    darkMode: false, // or 'media' or 'class'
    theme: {
        extend: {
            colors: {
                gray: colors.gray
            }
        }
    },
    variants: {
        extend: {},
    },
    plugins: [
        require('@tailwindcss/forms'),
    ],
}
